# Generated by Django 2.0.6 on 2018-10-12 13:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20181008_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentinfo',
            name='content',
            field=tinymce.models.HTMLField(max_length=500, verbose_name='评论内容'),
        ),
    ]
