# Generated by Django 2.0.6 on 2018-10-08 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='城市名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
            },
        ),
        migrations.CreateModel(
            name='OrgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机构名称')),
                ('image', models.ImageField(upload_to='org/%y/%m', verbose_name='机构图片')),
                ('study_num', models.IntegerField(default=0, verbose_name='学习人数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('love_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('address', models.CharField(max_length=200, verbose_name='机构地址')),
                ('desc', models.CharField(max_length=200, verbose_name='机构简介')),
                ('detail', models.TextField(verbose_name='机构详情')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('cityinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.CityInfo', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '机构信息',
                'verbose_name_plural': '机构信息',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='讲师姓名')),
                ('icon', models.ImageField(max_length=200, upload_to='teacher/%y/%m', verbose_name='讲师头像')),
                ('work_year', models.IntegerField(default=3, verbose_name='工作年限')),
                ('course_num', models.IntegerField(default=0, verbose_name='课程数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('love_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('work_style', models.CharField(max_length=100, verbose_name='教学特点')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='工作单位')),
                ('job', models.CharField(blank=True, max_length=20, null=True, verbose_name='职位')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('orginfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.OrgInfo', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '讲师信息',
                'verbose_name_plural': '讲师信息',
            },
        ),
    ]
