# Generated by Django 2.0.6 on 2018-10-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_orginfo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='age',
            field=models.IntegerField(default=20, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='study_know',
            field=models.CharField(default='好好学', max_length=100, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='teacher_say',
            field=models.CharField(default='好好学', max_length=100, verbose_name='老师说'),
        ),
    ]
