# Generated by Django 2.0.6 on 2018-10-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20181012_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='study_know',
            field=models.CharField(default='', max_length=100, verbose_name='课程须知'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_say',
            field=models.CharField(default='', max_length=100, verbose_name='老师说'),
        ),
    ]
