# Generated by Django 2.0.6 on 2018-10-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_auto_20181012_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='study_know',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='teacher_say',
        ),
    ]
