# Generated by Django 2.0.6 on 2018-10-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='study_know',
            field=models.CharField(default='', max_length=100, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='teacher_say',
            field=models.CharField(default='', max_length=100, verbose_name='老师说'),
        ),
    ]
