# Generated by Django 2.0.6 on 2018-10-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181012_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='category',
            field=models.CharField(choices=[('前端', '前端'), ('后端', '后端')], max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='level',
            field=models.CharField(choices=[('初级', '初级'), ('中级', '中级'), ('高级', '高级')], default='cj', max_length=20, verbose_name='课程难度'),
        ),
    ]
